### ISSUE TITLE
[Request] Add support for Mac OS X  

### ISSUE THREAD

**Issue by acerbetti** [YuAo/WAAccountStore#1]
I think your great work could be easily used on mac OS X. 

Can you please add the deployment target for osx in your pod spec?
s.osx.deployment_target = '10.7'

thanks

**Comment by YuAo** [comment]
Thanks. I'll review the code and add os x support.

**Comment by YuAo** [comment]
Done. Reference: deabb63b1692854b20f2e0f435d6574dd57bab51

**Comment by acerbetti** [comment]
Perfect, thanks for the quick patch
